version: '3.8'

services:

  frontend:
    image: dankstats-frontend:v1
    ports:
      - "3000:3000"

  api:
    image: dankstats-api:v1
    environment:
      TWITCH_CLIENT_ID:
      TWITCH_APP_ACCESS_TOKEN:
    ports:
      - "4000:4000"


  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
